/* ParserTokenManager.java */
/* Generated by: JJTree&ParserGeneratorCC: Do not edit this line. ParserTokenManager.java */
/*****************************************************************************
 * Licensed to the Apache Software Foundation (ASF) under one                *
 * or more contributor license agreements.  See the NOTICE file              *
 * distributed with this work for additional information                     *
 * regarding copyright ownership.  The ASF licenses this file                *
 * to you under the Apache License, Version 2.0 (the                         *
 * "License"); you may not use this file except in compliance                *
 * with the License.  You may obtain a copy of the License at                *
 *                                                                           *
 *     http://www.apache.org/licenses/LICENSE-2.0                            *
 *                                                                           *
 * Unless required by applicable law or agreed to in writing,                *
 * software distributed under the License is distributed on an               *
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY                    *
 * KIND, either express or implied.  See the License for the                 *
 * specific language governing permissions and limitations                   *
 * under the License.                                                        *
 *                                                                           *
 *                                                                           *
 * This file is part of the BeanShell Java Scripting distribution.           *
 * Documentation and updates may be found at http://www.beanshell.org/       *
 * Patrick Niemeyer (pat@pat.net)                                            *
 * Author of Learning Java, O'Reilly & Associates                            *
 *                                                                           *
 *****************************************************************************/
package bsh;
import java.io.IOException;
import java.io.Reader;
import java.util.ArrayList;
import java.util.List;

/** Token Manager. */
@SuppressWarnings ("unused")
public class ParserTokenManager implements ParserConstants {
private final int jjStopStringLiteralDfa_0(int pos, long active0, long active1, long active2){
   switch (pos)
   {
      case 0:
         if ((active0 & 0x1ffffffffffffc00L) != 0x0L || (active2 & 0x2000000L) != 0x0L)
         {
            jjmatchedKind = 72;
            return 35;
         }
         if ((active1 & 0x80000L) != 0x0L || (active2 & 0x800000L) != 0x0L)
            return 11;
         if ((active1 & 0x4000040000000000L) != 0x0L)
            return 62;
         if ((active0 & 0x3eL) != 0x0L)
            return 0;
         return -1;
      case 1:
         if ((active0 & 0x100600000L) != 0x0L)
            return 35;
         if ((active0 & 0x1ffffffeff9ffc00L) != 0x0L || (active2 & 0x2000000L) != 0x0L)
         {
            if (jjmatchedPos != 1)
            {
               jjmatchedKind = 72;
               jjmatchedPos = 1;
            }
            return 35;
         }
         return -1;
      case 2:
         if ((active0 & 0x100013040000000L) != 0x0L)
            return 35;
         if ((active0 & 0x1efffecebfdffc00L) != 0x0L || (active2 & 0x2000000L) != 0x0L)
         {
            if (jjmatchedPos != 2)
            {
               jjmatchedKind = 72;
               jjmatchedPos = 2;
            }
            return 35;
         }
         return -1;
      case 3:
         if ((active0 & 0xa8002408182c000L) != 0x0L)
            return 35;
         if ((active0 & 0x147ffcae3e5d3c00L) != 0x0L || (active2 & 0x2000000L) != 0x0L)
         {
            if (jjmatchedPos != 3)
            {
               jjmatchedKind = 72;
               jjmatchedPos = 3;
            }
            return 35;
         }
         return -1;
      case 4:
         if ((active0 & 0x106080003c053000L) != 0x0L)
            return 35;
         if ((active0 & 0x41f7cae02580c00L) != 0x0L || (active2 & 0x2000000L) != 0x0L)
         {
            if (jjmatchedPos != 4)
            {
               jjmatchedKind = 72;
               jjmatchedPos = 4;
            }
            return 35;
         }
         return -1;
      case 5:
         if ((active0 & 0x41a1c2a12180c00L) != 0x0L || (active2 & 0x2000000L) != 0x0L)
         {
            jjmatchedKind = 72;
            jjmatchedPos = 5;
            return 35;
         }
         if ((active0 & 0x45608400400000L) != 0x0L)
            return 35;
         return -1;
      case 6:
         if ((active0 & 0xc0012100800L) != 0x0L || (active2 & 0x2000000L) != 0x0L)
            return 35;
         if ((active0 & 0x41a102a00080400L) != 0x0L)
         {
            if (jjmatchedPos != 6)
            {
               jjmatchedKind = 72;
               jjmatchedPos = 6;
            }
            return 35;
         }
         return -1;
      case 7:
         if ((active0 & 0x402000000080400L) != 0x0L)
            return 35;
         if ((active0 & 0x18102a00000000L) != 0x0L)
         {
            jjmatchedKind = 72;
            jjmatchedPos = 7;
            return 35;
         }
         return -1;
      case 8:
         if ((active0 & 0x10102000000000L) != 0x0L)
            return 35;
         if ((active0 & 0x8000a00000000L) != 0x0L)
         {
            jjmatchedKind = 72;
            jjmatchedPos = 8;
            return 35;
         }
         return -1;
      case 9:
         if ((active0 & 0x8000000000000L) != 0x0L)
         {
            jjmatchedKind = 72;
            jjmatchedPos = 9;
            return 35;
         }
         if ((active0 & 0xa00000000L) != 0x0L)
            return 35;
         return -1;
      case 10:
         if ((active0 & 0x8000000000000L) != 0x0L)
         {
            if (jjmatchedPos != 10)
            {
               jjmatchedKind = 72;
               jjmatchedPos = 10;
            }
            return 35;
         }
         return -1;
      case 11:
         if ((active0 & 0x8000000000000L) != 0x0L)
            return 35;
         return -1;
      default :
         return -1;
   }
}
private final int jjStartNfa_0(int pos, long active0, long active1, long active2){
   return jjMoveNfa_0(jjStopStringLiteralDfa_0(pos, active0, active1, active2), pos + 1);
}
private int jjStopAtPos(int pos, int kind)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   return pos + 1;
}
private int jjMoveStringLiteralDfa0_0(){
   switch(curChar)
   {
      case 9:
         return jjStartNfaWithStates_0(0, 2, 0);
      case 10:
         return jjStartNfaWithStates_0(0, 5, 0);
      case 12:
         return jjStartNfaWithStates_0(0, 4, 0);
      case 13:
         return jjStartNfaWithStates_0(0, 3, 0);
      case ' ':
         return jjStartNfaWithStates_0(0, 1, 0);
      case '!':
         jjmatchedKind = 89;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x100000000L, 0x0L);
      case '%':
         jjmatchedKind = 113;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x0L, 0x20L);
      case '&':
         jjmatchedKind = 107;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x8000000800000000L, 0x0L);
      case '(':
         return jjStopAtPos(0, 75);
      case ')':
         return jjStopAtPos(0, 76);
      case '*':
         jjmatchedKind = 105;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x2008000000000000L, 0x80L);
      case '+':
         jjmatchedKind = 103;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x800002000000000L, 0x0L);
      case ',':
         return jjStopAtPos(0, 82);
      case '-':
         jjmatchedKind = 104;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x1000004000000000L, 0x8000L);
      case '.':
         jjmatchedKind = 83;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x0L, 0x800000L);
      case '/':
         jjmatchedKind = 106;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x4000000000000000L, 0x0L);
      case ':':
         jjmatchedKind = 149;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x0L, 0x400000L);
      case ';':
         return jjStopAtPos(0, 81);
      case '<':
         jjmatchedKind = 87;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x20000010000000L, 0x10200L);
      case '=':
         jjmatchedKind = 84;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x8000000L, 0x0L);
      case '>':
         jjmatchedKind = 85;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x280000040000000L, 0x2800L);
      case '?':
         jjmatchedKind = 148;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x0L, 0x10e0000L);
      case '@':
         return jjMoveStringLiteralDfa1_0(0x0L, 0x5555014a1400000L, 0x5555L);
      case '[':
         return jjStopAtPos(0, 79);
      case ']':
         return jjStopAtPos(0, 80);
      case '^':
         jjmatchedKind = 111;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x0L, 0x8L);
      case 'a':
         return jjMoveStringLiteralDfa1_0(0x400L, 0x0L, 0x0L);
      case 'b':
         return jjMoveStringLiteralDfa1_0(0x5800L, 0x0L, 0x0L);
      case 'c':
         return jjMoveStringLiteralDfa1_0(0xfa000L, 0x0L, 0x0L);
      case 'd':
         return jjMoveStringLiteralDfa1_0(0x700000L, 0x0L, 0x2000000L);
      case 'e':
         return jjMoveStringLiteralDfa1_0(0x3800000L, 0x0L, 0x0L);
      case 'f':
         return jjMoveStringLiteralDfa1_0(0x7c000000L, 0x0L, 0x0L);
      case 'g':
         return jjMoveStringLiteralDfa1_0(0x80000000L, 0x0L, 0x0L);
      case 'i':
         return jjMoveStringLiteralDfa1_0(0x3f00000000L, 0x0L, 0x0L);
      case 'l':
         return jjMoveStringLiteralDfa1_0(0x4000000000L, 0x0L, 0x0L);
      case 'n':
         return jjMoveStringLiteralDfa1_0(0x38000000000L, 0x0L, 0x0L);
      case 'p':
         return jjMoveStringLiteralDfa1_0(0x3c0000000000L, 0x0L, 0x0L);
      case 'r':
         return jjMoveStringLiteralDfa1_0(0x400000000000L, 0x0L, 0x0L);
      case 's':
         return jjMoveStringLiteralDfa1_0(0xf800000000000L, 0x0L, 0x0L);
      case 't':
         return jjMoveStringLiteralDfa1_0(0x1f0000000000000L, 0x0L, 0x0L);
      case 'v':
         return jjMoveStringLiteralDfa1_0(0x600000000000000L, 0x0L, 0x0L);
      case 'w':
         return jjMoveStringLiteralDfa1_0(0x1800000000000000L, 0x0L, 0x0L);
      case '{':
         return jjStopAtPos(0, 77);
      case '|':
         jjmatchedKind = 109;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x200000000L, 0x2L);
      case '}':
         return jjStopAtPos(0, 78);
      case '~':
         return jjStopAtPos(0, 90);
      default :
         return jjMoveNfa_0(6, 0);
   }
}
private int jjMoveStringLiteralDfa1_0(long active0, long active1, long active2){
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(0, active0, active1, active2);
      return 1;
   }
   switch(curChar)
   {
      case '&':
         if ((active1 & 0x800000000L) != 0x0L)
            return jjStopAtPos(1, 99);
         break;
      case '*':
         if ((active1 & 0x8000000000000L) != 0x0L)
         {
            jjmatchedKind = 115;
            jjmatchedPos = 1;
         }
         return jjMoveStringLiteralDfa2_0(active0, 0x0L, active1, 0x0L, active2, 0x80L);
      case '+':
         if ((active1 & 0x2000000000L) != 0x0L)
            return jjStopAtPos(1, 101);
         break;
      case '-':
         if ((active1 & 0x4000000000L) != 0x0L)
            return jjStopAtPos(1, 102);
         break;
      case '.':
         if ((active2 & 0x1000000L) != 0x0L)
            return jjStopAtPos(1, 152);
         return jjMoveStringLiteralDfa2_0(active0, 0x0L, active1, 0x0L, active2, 0x800000L);
      case ':':
         if ((active2 & 0x80000L) != 0x0L)
            return jjStopAtPos(1, 147);
         else if ((active2 & 0x400000L) != 0x0L)
            return jjStopAtPos(1, 150);
         break;
      case '<':
         if ((active1 & 0x20000000000000L) != 0x0L)
         {
            jjmatchedKind = 117;
            jjmatchedPos = 1;
         }
         return jjMoveStringLiteralDfa2_0(active0, 0x0L, active1, 0x0L, active2, 0x200L);
      case '=':
         if ((active1 & 0x8000000L) != 0x0L)
            return jjStopAtPos(1, 91);
         else if ((active1 & 0x10000000L) != 0x0L)
         {
            jjmatchedKind = 92;
            jjmatchedPos = 1;
         }
         else if ((active1 & 0x40000000L) != 0x0L)
            return jjStopAtPos(1, 94);
         else if ((active1 & 0x100000000L) != 0x0L)
            return jjStopAtPos(1, 96);
         else if ((active1 & 0x800000000000000L) != 0x0L)
            return jjStopAtPos(1, 123);
         else if ((active1 & 0x1000000000000000L) != 0x0L)
            return jjStopAtPos(1, 124);
         else if ((active1 & 0x2000000000000000L) != 0x0L)
            return jjStopAtPos(1, 125);
         else if ((active1 & 0x4000000000000000L) != 0x0L)
            return jjStopAtPos(1, 126);
         else if ((active1 & 0x8000000000000000L) != 0x0L)
            return jjStopAtPos(1, 127);
         else if ((active2 & 0x2L) != 0x0L)
            return jjStopAtPos(1, 129);
         else if ((active2 & 0x8L) != 0x0L)
            return jjStopAtPos(1, 131);
         else if ((active2 & 0x20L) != 0x0L)
            return jjStopAtPos(1, 133);
         return jjMoveStringLiteralDfa2_0(active0, 0x0L, active1, 0x0L, active2, 0x10000L);
      case '>':
         if ((active1 & 0x80000000000000L) != 0x0L)
         {
            jjmatchedKind = 119;
            jjmatchedPos = 1;
         }
         else if ((active2 & 0x8000L) != 0x0L)
            return jjStopAtPos(1, 143);
         return jjMoveStringLiteralDfa2_0(active0, 0x0L, active1, 0x200000000000000L, active2, 0x2800L);
      case '?':
         if ((active2 & 0x40000L) != 0x0L)
         {
            jjmatchedKind = 146;
            jjmatchedPos = 1;
         }
         return jjMoveStringLiteralDfa2_0(active0, 0x0L, active1, 0x0L, active2, 0x20000L);
      case 'a':
         return jjMoveStringLiteralDfa2_0(active0, 0x48004018000L, active1, 0x1000000000L, active2, 0x1L);
      case 'b':
         return jjMoveStringLiteralDfa2_0(active0, 0x400L, active1, 0x1500000000000L, active2, 0x0L);
      case 'e':
         return jjMoveStringLiteralDfa2_0(active0, 0x410000100000L, active1, 0x0L, active2, 0x2000000L);
      case 'f':
         if ((active0 & 0x100000000L) != 0x0L)
            return jjStartNfaWithStates_0(1, 32, 35);
         break;
      case 'g':
         return jjMoveStringLiteralDfa2_0(active0, 0x0L, active1, 0x80400000L, active2, 0x0L);
      case 'h':
         return jjMoveStringLiteralDfa2_0(active0, 0x1860800000020000L, active1, 0x0L, active2, 0x0L);
      case 'i':
         return jjMoveStringLiteralDfa2_0(active0, 0x18000000L, active1, 0x0L, active2, 0x0L);
      case 'l':
         return jjMoveStringLiteralDfa2_0(active0, 0x20802000L, active1, 0x40000021000000L, active2, 0x400L);
      case 'm':
         return jjMoveStringLiteralDfa2_0(active0, 0x600000000L, active1, 0x4000000000000L, active2, 0x40L);
      case 'n':
         return jjMoveStringLiteralDfa2_0(active0, 0x3801000000L, active1, 0x0L, active2, 0x0L);
      case 'o':
         if ((active0 & 0x200000L) != 0x0L)
         {
            jjmatchedKind = 21;
            jjmatchedPos = 1;
         }
         return jjMoveStringLiteralDfa2_0(active0, 0x6000040c04c0800L, active1, 0x400000000L, active2, 0x4L);
      case 'p':
         return jjMoveStringLiteralDfa2_0(active0, 0x0L, active1, 0x10000000000000L, active2, 0x100L);
      case 'r':
         return jjMoveStringLiteralDfa2_0(active0, 0x190180000001000L, active1, 0x500000000000000L, active2, 0x5000L);
      case 't':
         return jjMoveStringLiteralDfa2_0(active0, 0x3000000000000L, active1, 0x0L, active2, 0x0L);
      case 'u':
         return jjMoveStringLiteralDfa2_0(active0, 0x220000000000L, active1, 0x0L, active2, 0x0L);
      case 'w':
         return jjMoveStringLiteralDfa2_0(active0, 0x4000000000000L, active1, 0x0L, active2, 0x0L);
      case 'x':
         return jjMoveStringLiteralDfa2_0(active0, 0x2000000L, active1, 0x0L, active2, 0x10L);
      case 'y':
         return jjMoveStringLiteralDfa2_0(active0, 0x8000000004000L, active1, 0x0L, active2, 0x0L);
      case '|':
         if ((active1 & 0x200000000L) != 0x0L)
            return jjStopAtPos(1, 97);
         break;
      default :
         break;
   }
   return jjStartNfa_0(0, active0, active1, active2);
}
private int jjMoveStringLiteralDfa2_0(long old0, long active0, long old1, long active1, long old2, long active2){
   if (((active0 &= old0) | (active1 &= old1) | (active2 &= old2)) == 0L)
      return jjStartNfa_0(0, old0, old1, old2);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(1, active0, active1, active2);
      return 2;
   }
   switch(curChar)
   {
      case '.':
         if ((active2 & 0x800000L) != 0x0L)
            return jjStopAtPos(2, 151);
         break;
      case '=':
         if ((active2 & 0x80L) != 0x0L)
            return jjStopAtPos(2, 135);
         else if ((active2 & 0x200L) != 0x0L)
            return jjStopAtPos(2, 137);
         else if ((active2 & 0x800L) != 0x0L)
            return jjStopAtPos(2, 139);
         else if ((active2 & 0x20000L) != 0x0L)
            return jjStopAtPos(2, 145);
         break;
      case '>':
         if ((active1 & 0x200000000000000L) != 0x0L)
         {
            jjmatchedKind = 121;
            jjmatchedPos = 2;
         }
         else if ((active2 & 0x10000L) != 0x0L)
            return jjStopAtPos(2, 144);
         return jjMoveStringLiteralDfa3_0(active0, 0x0L, active1, 0x0L, active2, 0x2000L);
      case 'a':
         return jjMoveStringLiteralDfa3_0(active0, 0x11000000022000L, active1, 0x0L, active2, 0x0L);
      case 'b':
         return jjMoveStringLiteralDfa3_0(active0, 0x200000000000L, active1, 0x0L, active2, 0x0L);
      case 'c':
         return jjMoveStringLiteralDfa3_0(active0, 0x40000000000L, active1, 0x0L, active2, 0x0L);
      case 'e':
         return jjMoveStringLiteralDfa3_0(active0, 0x800000000001000L, active1, 0x40000000000000L, active2, 0x400L);
      case 'f':
         return jjMoveStringLiteralDfa3_0(active0, 0x100000L, active1, 0x0L, active2, 0x2000000L);
      case 'i':
         return jjMoveStringLiteralDfa3_0(active0, 0x1204080000000000L, active1, 0x501500000000000L, active2, 0x5000L);
      case 'l':
         return jjMoveStringLiteralDfa3_0(active0, 0x400020004000000L, active1, 0x0L, active2, 0x0L);
      case 'n':
         return jjMoveStringLiteralDfa3_0(active0, 0x80040180c0000L, active1, 0x1000000000L, active2, 0x1L);
      case 'o':
         return jjMoveStringLiteralDfa3_0(active0, 0x900020000800L, active1, 0x14000000000000L, active2, 0x150L);
      case 'p':
         return jjMoveStringLiteralDfa3_0(active0, 0x600000000L, active1, 0x0L, active2, 0x0L);
      case 'r':
         if ((active0 & 0x40000000L) != 0x0L)
            return jjStartNfaWithStates_0(2, 30, 35);
         else if ((active1 & 0x400000000L) != 0x0L)
         {
            jjmatchedKind = 98;
            jjmatchedPos = 2;
         }
         return jjMoveStringLiteralDfa3_0(active0, 0x62000000000000L, active1, 0x0L, active2, 0x4L);
      case 's':
         return jjMoveStringLiteralDfa3_0(active0, 0x800808400L, active1, 0x0L, active2, 0x0L);
      case 't':
         if ((active0 & 0x1000000000L) != 0x0L)
         {
            jjmatchedKind = 36;
            jjmatchedPos = 2;
         }
         else if ((active1 & 0x400000L) != 0x0L)
         {
            jjmatchedKind = 86;
            jjmatchedPos = 2;
         }
         else if ((active1 & 0x1000000L) != 0x0L)
         {
            jjmatchedKind = 88;
            jjmatchedPos = 2;
         }
         return jjMoveStringLiteralDfa3_0(active0, 0x40a082014000L, active1, 0xa0000000L, active2, 0x0L);
      case 'u':
         return jjMoveStringLiteralDfa3_0(active0, 0x80000001400000L, active1, 0x0L, active2, 0x0L);
      case 'w':
         if ((active0 & 0x10000000000L) != 0x0L)
            return jjStartNfaWithStates_0(2, 40, 35);
         break;
      case 'y':
         if ((active0 & 0x100000000000000L) != 0x0L)
            return jjStartNfaWithStates_0(2, 56, 35);
         break;
      default :
         break;
   }
   return jjStartNfa_0(1, active0, active1, active2);
}
private int jjMoveStringLiteralDfa3_0(long old0, long active0, long old1, long active1, long old2, long active2){
   if (((active0 &= old0) | (active1 &= old1) | (active2 &= old2)) == 0L)
      return jjStartNfa_0(1, old0, old1, old2);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(2, active0, active1, active2);
      return 3;
   }
   switch(curChar)
   {
      case '=':
         if ((active2 & 0x2000L) != 0x0L)
            return jjStopAtPos(3, 141);
         break;
      case '_':
         return jjMoveStringLiteralDfa4_0(active0, 0x0L, active1, 0x0L, active2, 0x4L);
      case 'a':
         return jjMoveStringLiteralDfa4_0(active0, 0x400000038101000L, active1, 0x0L, active2, 0x2000000L);
      case 'b':
         return jjMoveStringLiteralDfa4_0(active0, 0x400000L, active1, 0x0L, active2, 0x0L);
      case 'c':
         return jjMoveStringLiteralDfa4_0(active0, 0x8000000010000L, active1, 0x0L, active2, 0x0L);
      case 'd':
         if ((active0 & 0x200000000000000L) != 0x0L)
            return jjStartNfaWithStates_0(3, 57, 35);
         else if ((active1 & 0x1000000000L) != 0x0L)
         {
            jjmatchedKind = 100;
            jjmatchedPos = 3;
         }
         else if ((active1 & 0x4000000000000L) != 0x0L)
         {
            jjmatchedKind = 114;
            jjmatchedPos = 3;
         }
         return jjMoveStringLiteralDfa4_0(active0, 0x0L, active1, 0x0L, active2, 0x41L);
      case 'e':
         if ((active0 & 0x4000L) != 0x0L)
            return jjStartNfaWithStates_0(3, 14, 35);
         else if ((active0 & 0x8000L) != 0x0L)
            return jjStartNfaWithStates_0(3, 15, 35);
         else if ((active0 & 0x800000L) != 0x0L)
            return jjStartNfaWithStates_0(3, 23, 35);
         else if ((active0 & 0x80000000000000L) != 0x0L)
            return jjStartNfaWithStates_0(3, 55, 35);
         return jjMoveStringLiteralDfa4_0(active0, 0x2002000000L, active1, 0xa0000000L, active2, 0x0L);
      case 'f':
         return jjMoveStringLiteralDfa4_0(active0, 0x0L, active1, 0x40000000000000L, active2, 0x400L);
      case 'g':
         if ((active0 & 0x4000000000L) != 0x0L)
            return jjStartNfaWithStates_0(3, 38, 35);
         return jjMoveStringLiteralDfa4_0(active0, 0x0L, active1, 0x500000000000000L, active2, 0x5000L);
      case 'i':
         return jjMoveStringLiteralDfa4_0(active0, 0x2008000000000L, active1, 0x0L, active2, 0x0L);
      case 'k':
         return jjMoveStringLiteralDfa4_0(active0, 0x40000000000L, active1, 0x0L, active2, 0x0L);
      case 'l':
         if ((active0 & 0x20000000000L) != 0x0L)
            return jjStartNfaWithStates_0(3, 41, 35);
         return jjMoveStringLiteralDfa4_0(active0, 0x1000200200000800L, active1, 0x0L, active2, 0x0L);
      case 'm':
         if ((active0 & 0x1000000L) != 0x0L)
            return jjStartNfaWithStates_0(3, 24, 35);
         break;
      case 'n':
         if ((active0 & 0x800000000000000L) != 0x0L)
            return jjStartNfaWithStates_0(3, 59, 35);
         return jjMoveStringLiteralDfa4_0(active0, 0x10000000000000L, active1, 0x0L, active2, 0x0L);
      case 'o':
         if ((active0 & 0x80000000L) != 0x0L)
            return jjStartNfaWithStates_0(3, 31, 35);
         return jjMoveStringLiteralDfa4_0(active0, 0x60000400000000L, active1, 0x0L, active2, 0x0L);
      case 'r':
         if ((active0 & 0x20000L) != 0x0L)
            return jjStartNfaWithStates_0(3, 17, 35);
         return jjMoveStringLiteralDfa4_0(active0, 0x800000000000L, active1, 0x0L, active2, 0x10L);
      case 's':
         return jjMoveStringLiteralDfa4_0(active0, 0x4042000L, active1, 0x0L, active2, 0x0L);
      case 't':
         return jjMoveStringLiteralDfa4_0(active0, 0x5100800080400L, active1, 0x1500000000000L, active2, 0x0L);
      case 'u':
         return jjMoveStringLiteralDfa4_0(active0, 0x400000000000L, active1, 0x0L, active2, 0x0L);
      case 'v':
         return jjMoveStringLiteralDfa4_0(active0, 0x80000000000L, active1, 0x0L, active2, 0x0L);
      case 'w':
         if ((active1 & 0x10000000000000L) != 0x0L)
         {
            jjmatchedKind = 116;
            jjmatchedPos = 3;
         }
         return jjMoveStringLiteralDfa4_0(active0, 0x0L, active1, 0x0L, active2, 0x100L);
      default :
         break;
   }
   return jjStartNfa_0(2, active0, active1, active2);
}
private int jjMoveStringLiteralDfa4_0(long old0, long active0, long old1, long active1, long old2, long active2){
   if (((active0 &= old0) | (active1 &= old1) | (active2 &= old2)) == 0L)
      return jjStartNfa_0(2, old0, old1, old2);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(3, active0, active1, active2);
      return 4;
   }
   switch(curChar)
   {
      case '_':
         return jjMoveStringLiteralDfa5_0(active0, 0x0L, active1, 0x0L, active2, 0x151L);
      case 'a':
         return jjMoveStringLiteralDfa5_0(active0, 0xc0800000000L, active1, 0x0L, active2, 0x4L);
      case 'c':
         return jjMoveStringLiteralDfa5_0(active0, 0x6000000000000L, active1, 0x0L, active2, 0x0L);
      case 'e':
         if ((active0 & 0x4000000L) != 0x0L)
            return jjStartNfaWithStates_0(4, 26, 35);
         else if ((active0 & 0x1000000000000000L) != 0x0L)
            return jjStartNfaWithStates_0(4, 60, 35);
         return jjMoveStringLiteralDfa5_0(active0, 0x100200000800L, active1, 0x0L, active2, 0x0L);
      case 'h':
         if ((active0 & 0x10000L) != 0x0L)
            return jjStartNfaWithStates_0(4, 16, 35);
         return jjMoveStringLiteralDfa5_0(active0, 0x8000000000000L, active1, 0x500000000000000L, active2, 0x5000L);
      case 'i':
         return jjMoveStringLiteralDfa5_0(active0, 0x1200000080000L, active1, 0x0L, active2, 0x0L);
      case 'k':
         if ((active0 & 0x1000L) != 0x0L)
            return jjStartNfaWithStates_0(4, 12, 35);
         break;
      case 'l':
         if ((active0 & 0x8000000L) != 0x0L)
         {
            jjmatchedKind = 27;
            jjmatchedPos = 4;
         }
         return jjMoveStringLiteralDfa5_0(active0, 0x10400000L, active1, 0x0L, active2, 0x0L);
      case 'n':
         return jjMoveStringLiteralDfa5_0(active0, 0x2000000L, active1, 0x0L, active2, 0x0L);
      case 'q':
         if ((active1 & 0x20000000L) != 0x0L)
            return jjStopAtPos(4, 93);
         else if ((active1 & 0x80000000L) != 0x0L)
            return jjStopAtPos(4, 95);
         break;
      case 'r':
         return jjMoveStringLiteralDfa5_0(active0, 0x402400000400L, active1, 0x0L, active2, 0x0L);
      case 's':
         if ((active0 & 0x2000L) != 0x0L)
            return jjStartNfaWithStates_0(4, 13, 35);
         return jjMoveStringLiteralDfa5_0(active0, 0x10000000000000L, active1, 0x0L, active2, 0x0L);
      case 't':
         if ((active0 & 0x40000L) != 0x0L)
            return jjStartNfaWithStates_0(4, 18, 35);
         else if ((active0 & 0x20000000L) != 0x0L)
            return jjStartNfaWithStates_0(4, 29, 35);
         else if ((active0 & 0x800000000000L) != 0x0L)
            return jjStartNfaWithStates_0(4, 47, 35);
         return jjMoveStringLiteralDfa5_0(active0, 0x400000000000000L, active1, 0x40000000000000L, active2, 0x400L);
      case 'u':
         return jjMoveStringLiteralDfa5_0(active0, 0x100000L, active1, 0x0L, active2, 0x2000000L);
      case 'v':
         return jjMoveStringLiteralDfa5_0(active0, 0x8000000000L, active1, 0x0L, active2, 0x0L);
      case 'w':
         if ((active0 & 0x20000000000000L) != 0x0L)
         {
            jjmatchedKind = 53;
            jjmatchedPos = 4;
         }
         return jjMoveStringLiteralDfa5_0(active0, 0x40000000000000L, active1, 0x1500000000000L, active2, 0x0L);
      default :
         break;
   }
   return jjStartNfa_0(3, active0, active1, active2);
}
private int jjMoveStringLiteralDfa5_0(long old0, long active0, long old1, long active1, long old2, long active2){
   if (((active0 &= old0) | (active1 &= old1) | (active2 &= old2)) == 0L)
      return jjStartNfa_0(3, old0, old1, old2);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(4, active0, active1, active2);
      return 5;
   }
   switch(curChar)
   {
      case '_':
         return jjMoveStringLiteralDfa6_0(active0, 0x0L, active1, 0x40000000000000L, active2, 0x400L);
      case 'a':
         return jjMoveStringLiteralDfa6_0(active0, 0xc00L, active1, 0x0L, active2, 0x151L);
      case 'c':
         if ((active0 & 0x200000000000L) != 0x0L)
            return jjStartNfaWithStates_0(5, 45, 35);
         else if ((active0 & 0x1000000000000L) != 0x0L)
            return jjStartNfaWithStates_0(5, 48, 35);
         return jjMoveStringLiteralDfa6_0(active0, 0x100000000000L, active1, 0x0L, active2, 0x0L);
      case 'd':
         return jjMoveStringLiteralDfa6_0(active0, 0x2000000L, active1, 0x0L, active2, 0x0L);
      case 'e':
         if ((active0 & 0x400000L) != 0x0L)
            return jjStartNfaWithStates_0(5, 22, 35);
         else if ((active0 & 0x8000000000L) != 0x0L)
            return jjStartNfaWithStates_0(5, 39, 35);
         break;
      case 'f':
         return jjMoveStringLiteralDfa6_0(active0, 0x2000000000L, active1, 0x0L, active2, 0x0L);
      case 'g':
         return jjMoveStringLiteralDfa6_0(active0, 0x40000000000L, active1, 0x0L, active2, 0x0L);
      case 'h':
         if ((active0 & 0x4000000000000L) != 0x0L)
            return jjStartNfaWithStates_0(5, 50, 35);
         break;
      case 'i':
         return jjMoveStringLiteralDfa6_0(active0, 0x410000000000000L, active1, 0x1500000000000L, active2, 0x0L);
      case 'l':
         return jjMoveStringLiteralDfa6_0(active0, 0x10100000L, active1, 0x0L, active2, 0x2000000L);
      case 'm':
         return jjMoveStringLiteralDfa6_0(active0, 0x200000000L, active1, 0x0L, active2, 0x0L);
      case 'n':
         if ((active0 & 0x400000000000L) != 0x0L)
            return jjStartNfaWithStates_0(5, 46, 35);
         return jjMoveStringLiteralDfa6_0(active0, 0x800080000L, active1, 0x0L, active2, 0x0L);
      case 'r':
         return jjMoveStringLiteralDfa6_0(active0, 0x8000000000000L, active1, 0x0L, active2, 0x0L);
      case 's':
         if ((active0 & 0x40000000000000L) != 0x0L)
            return jjStartNfaWithStates_0(5, 54, 35);
         return jjMoveStringLiteralDfa6_0(active0, 0x0L, active1, 0x0L, active2, 0x4L);
      case 't':
         if ((active0 & 0x400000000L) != 0x0L)
            return jjStartNfaWithStates_0(5, 34, 35);
         return jjMoveStringLiteralDfa6_0(active0, 0x2080000000000L, active1, 0x500000000000000L, active2, 0x5000L);
      default :
         break;
   }
   return jjStartNfa_0(4, active0, active1, active2);
}
private int jjMoveStringLiteralDfa6_0(long old0, long active0, long old1, long active1, long old2, long active2){
   if (((active0 &= old0) | (active1 &= old1) | (active2 &= old2)) == 0L)
      return jjStartNfa_0(4, old0, old1, old2);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(5, active0, active1, active2);
      return 6;
   }
   switch(curChar)
   {
      case '_':
         return jjMoveStringLiteralDfa7_0(active0, 0x0L, active1, 0x500000000000000L, active2, 0x5000L);
      case 'a':
         return jjMoveStringLiteralDfa7_0(active0, 0x2000000000L, active1, 0x0L, active2, 0x0L);
      case 'c':
         return jjMoveStringLiteralDfa7_0(active0, 0x800000400L, active1, 0x0L, active2, 0x0L);
      case 'e':
         if ((active0 & 0x40000000000L) != 0x0L)
            return jjStartNfaWithStates_0(6, 42, 35);
         else if ((active0 & 0x80000000000L) != 0x0L)
            return jjStartNfaWithStates_0(6, 43, 35);
         return jjMoveStringLiteralDfa7_0(active0, 0x10000200000000L, active1, 0x0L, active2, 0x0L);
      case 'f':
         return jjMoveStringLiteralDfa7_0(active0, 0x2000000000000L, active1, 0x0L, active2, 0x0L);
      case 'l':
         return jjMoveStringLiteralDfa7_0(active0, 0x400000000000000L, active1, 0x0L, active2, 0x0L);
      case 'n':
         if ((active0 & 0x800L) != 0x0L)
            return jjStartNfaWithStates_0(6, 11, 35);
         break;
      case 'o':
         return jjMoveStringLiteralDfa7_0(active0, 0x8000000000000L, active1, 0x0L, active2, 0x0L);
      case 's':
         if ((active0 & 0x2000000L) != 0x0L)
            return jjStartNfaWithStates_0(6, 25, 35);
         return jjMoveStringLiteralDfa7_0(active0, 0x0L, active1, 0x41500000000000L, active2, 0x555L);
      case 't':
         if ((active0 & 0x100000L) != 0x0L)
         {
            jjmatchedKind = 20;
            jjmatchedPos = 6;
         }
         return jjMoveStringLiteralDfa7_0(active0, 0x100000000000L, active1, 0x0L, active2, 0x2000000L);
      case 'u':
         return jjMoveStringLiteralDfa7_0(active0, 0x80000L, active1, 0x0L, active2, 0x0L);
      case 'y':
         if ((active0 & 0x10000000L) != 0x0L)
            return jjStartNfaWithStates_0(6, 28, 35);
         break;
      default :
         break;
   }
   return jjStartNfa_0(5, active0, active1, active2);
}
private int jjMoveStringLiteralDfa7_0(long old0, long active0, long old1, long active1, long old2, long active2){
   if (((active0 &= old0) | (active1 &= old1) | (active2 &= old2)) == 0L)
      return jjStartNfa_0(5, old0, old1, old2);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(6, active0, active1, active2);
      return 7;
   }
   switch(curChar)
   {
      case ':':
         if ((active2 & 0x2000000L) != 0x0L)
            return jjStopAtPos(7, 153);
         break;
      case 'c':
         return jjMoveStringLiteralDfa8_0(active0, 0x2000000000L, active1, 0x0L, active2, 0x0L);
      case 'e':
         if ((active0 & 0x80000L) != 0x0L)
            return jjStartNfaWithStates_0(7, 19, 35);
         else if ((active0 & 0x400000000000000L) != 0x0L)
            return jjStartNfaWithStates_0(7, 58, 35);
         return jjMoveStringLiteralDfa8_0(active0, 0x100800000000L, active1, 0x1500000000000L, active2, 0x0L);
      case 'h':
         return jjMoveStringLiteralDfa8_0(active0, 0x0L, active1, 0x40000000000000L, active2, 0x400L);
      case 'i':
         return jjMoveStringLiteralDfa8_0(active0, 0x0L, active1, 0x0L, active2, 0x4L);
      case 'n':
         return jjMoveStringLiteralDfa8_0(active0, 0x18000200000000L, active1, 0x0L, active2, 0x0L);
      case 'p':
         if ((active0 & 0x2000000000000L) != 0x0L)
            return jjStartNfaWithStates_0(7, 49, 35);
         break;
      case 's':
         return jjMoveStringLiteralDfa8_0(active0, 0x0L, active1, 0x100000000000000L, active2, 0x1151L);
      case 't':
         if ((active0 & 0x400L) != 0x0L)
            return jjStartNfaWithStates_0(7, 10, 35);
         break;
      case 'u':
         return jjMoveStringLiteralDfa8_0(active0, 0x0L, active1, 0x400000000000000L, active2, 0x4000L);
      default :
         break;
   }
   return jjStartNfa_0(6, active0, active1, active2);
}
private int jjMoveStringLiteralDfa8_0(long old0, long active0, long old1, long active1, long old2, long active2){
   if (((active0 &= old0) | (active1 &= old1) | (active2 &= old2)) == 0L)
      return jjStartNfa_0(6, old0, old1, old2);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(7, active0, active1, active2);
      return 8;
   }
   switch(curChar)
   {
      case '_':
         return jjMoveStringLiteralDfa9_0(active0, 0x0L, active1, 0x1500000000000L, active2, 0x0L);
      case 'd':
         if ((active0 & 0x100000000000L) != 0x0L)
            return jjStartNfaWithStates_0(8, 44, 35);
         break;
      case 'e':
         if ((active0 & 0x2000000000L) != 0x0L)
            return jjStartNfaWithStates_0(8, 37, 35);
         break;
      case 'g':
         return jjMoveStringLiteralDfa9_0(active0, 0x0L, active1, 0x0L, active2, 0x4L);
      case 'h':
         return jjMoveStringLiteralDfa9_0(active0, 0x0L, active1, 0x100000000000000L, active2, 0x1000L);
      case 'i':
         return jjMoveStringLiteralDfa9_0(active0, 0x8000000000000L, active1, 0x40000000000000L, active2, 0x551L);
      case 'n':
         return jjMoveStringLiteralDfa9_0(active0, 0x0L, active1, 0x400000000000000L, active2, 0x4000L);
      case 'o':
         return jjMoveStringLiteralDfa9_0(active0, 0x800000000L, active1, 0x0L, active2, 0x0L);
      case 't':
         if ((active0 & 0x10000000000000L) != 0x0L)
            return jjStartNfaWithStates_0(8, 52, 35);
         return jjMoveStringLiteralDfa9_0(active0, 0x200000000L, active1, 0x0L, active2, 0x0L);
      default :
         break;
   }
   return jjStartNfa_0(7, active0, active1, active2);
}
private int jjMoveStringLiteralDfa9_0(long old0, long active0, long old1, long active1, long old2, long active2){
   if (((active0 &= old0) | (active1 &= old1) | (active2 &= old2)) == 0L)
      return jjStartNfa_0(7, old0, old1, old2);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(8, active0, active1, active2);
      return 9;
   }
   switch(curChar)
   {
      case 'a':
         return jjMoveStringLiteralDfa10_0(active0, 0x0L, active1, 0x100000000000L, active2, 0x0L);
      case 'f':
         if ((active0 & 0x800000000L) != 0x0L)
            return jjStartNfaWithStates_0(9, 35, 35);
         return jjMoveStringLiteralDfa10_0(active0, 0x0L, active1, 0x40000000000000L, active2, 0x400L);
      case 'g':
         return jjMoveStringLiteralDfa10_0(active0, 0x0L, active1, 0x0L, active2, 0x151L);
      case 'i':
         return jjMoveStringLiteralDfa10_0(active0, 0x0L, active1, 0x100000000000000L, active2, 0x1000L);
      case 'n':
         if ((active2 & 0x4L) != 0x0L)
            return jjStopAtPos(9, 130);
         break;
      case 'o':
         return jjMoveStringLiteralDfa10_0(active0, 0x0L, active1, 0x400000000000L, active2, 0x0L);
      case 's':
         if ((active0 & 0x200000000L) != 0x0L)
            return jjStartNfaWithStates_0(9, 33, 35);
         return jjMoveStringLiteralDfa10_0(active0, 0x0L, active1, 0x400000000000000L, active2, 0x4000L);
      case 'x':
         return jjMoveStringLiteralDfa10_0(active0, 0x0L, active1, 0x1000000000000L, active2, 0x0L);
      case 'z':
         return jjMoveStringLiteralDfa10_0(active0, 0x8000000000000L, active1, 0x0L, active2, 0x0L);
      default :
         break;
   }
   return jjStartNfa_0(8, active0, active1, active2);
}
private int jjMoveStringLiteralDfa10_0(long old0, long active0, long old1, long active1, long old2, long active2){
   if (((active0 &= old0) | (active1 &= old1) | (active2 &= old2)) == 0L)
      return jjStartNfa_0(8, old0, old1, old2);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(9, active0, active1, active2);
      return 10;
   }
   switch(curChar)
   {
      case 'e':
         return jjMoveStringLiteralDfa11_0(active0, 0x8000000000000L, active1, 0x0L, active2, 0x0L);
      case 'f':
         return jjMoveStringLiteralDfa11_0(active0, 0x0L, active1, 0x100000000000000L, active2, 0x1000L);
      case 'i':
         return jjMoveStringLiteralDfa11_0(active0, 0x0L, active1, 0x400000000000000L, active2, 0x4000L);
      case 'n':
         if ((active2 & 0x1L) != 0x0L)
            return jjStopAtPos(10, 128);
         else if ((active2 & 0x10L) != 0x0L)
            return jjStopAtPos(10, 132);
         else if ((active2 & 0x40L) != 0x0L)
            return jjStopAtPos(10, 134);
         else if ((active2 & 0x100L) != 0x0L)
            return jjStopAtPos(10, 136);
         return jjMoveStringLiteralDfa11_0(active0, 0x0L, active1, 0x100000000000L, active2, 0x0L);
      case 'o':
         return jjMoveStringLiteralDfa11_0(active0, 0x0L, active1, 0x1000000000000L, active2, 0x0L);
      case 'r':
         if ((active1 & 0x400000000000L) != 0x0L)
            return jjStopAtPos(10, 110);
         break;
      case 't':
         if ((active1 & 0x40000000000000L) != 0x0L)
         {
            jjmatchedKind = 118;
            jjmatchedPos = 10;
         }
         return jjMoveStringLiteralDfa11_0(active0, 0x0L, active1, 0x0L, active2, 0x400L);
      default :
         break;
   }
   return jjStartNfa_0(9, active0, active1, active2);
}
private int jjMoveStringLiteralDfa11_0(long old0, long active0, long old1, long active1, long old2, long active2){
   if (((active0 &= old0) | (active1 &= old1) | (active2 &= old2)) == 0L)
      return jjStartNfa_0(9, old0, old1, old2);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(10, active0, active1, active2);
      return 11;
   }
   switch(curChar)
   {
      case '_':
         return jjMoveStringLiteralDfa12_0(active0, 0x0L, active1, 0x0L, active2, 0x400L);
      case 'd':
         if ((active0 & 0x8000000000000L) != 0x0L)
            return jjStartNfaWithStates_0(11, 51, 35);
         else if ((active1 & 0x100000000000L) != 0x0L)
            return jjStopAtPos(11, 108);
         break;
      case 'g':
         return jjMoveStringLiteralDfa12_0(active0, 0x0L, active1, 0x400000000000000L, active2, 0x4000L);
      case 'r':
         if ((active1 & 0x1000000000000L) != 0x0L)
            return jjStopAtPos(11, 112);
         break;
      case 't':
         if ((active1 & 0x100000000000000L) != 0x0L)
         {
            jjmatchedKind = 120;
            jjmatchedPos = 11;
         }
         return jjMoveStringLiteralDfa12_0(active0, 0x0L, active1, 0x0L, active2, 0x1000L);
      default :
         break;
   }
   return jjStartNfa_0(10, active0, active1, active2);
}
private int jjMoveStringLiteralDfa12_0(long old0, long active0, long old1, long active1, long old2, long active2){
   if (((active0 &= old0) | (active1 &= old1) | (active2 &= old2)) == 0L)
      return jjStartNfa_0(10, old0, old1, old2);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(11, 0L, active1, active2);
      return 12;
   }
   switch(curChar)
   {
      case '_':
         return jjMoveStringLiteralDfa13_0(active1, 0x0L, active2, 0x1000L);
      case 'a':
         return jjMoveStringLiteralDfa13_0(active1, 0x0L, active2, 0x400L);
      case 'n':
         return jjMoveStringLiteralDfa13_0(active1, 0x400000000000000L, active2, 0x4000L);
      default :
         break;
   }
   return jjStartNfa_0(11, 0L, active1, active2);
}
private int jjMoveStringLiteralDfa13_0(long old1, long active1, long old2, long active2){
   if (((active1 &= old1) | (active2 &= old2)) == 0L)
      return jjStartNfa_0(11, 0L, old1, old2);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(12, 0L, active1, active2);
      return 13;
   }
   switch(curChar)
   {
      case 'a':
         return jjMoveStringLiteralDfa14_0(active1, 0x0L, active2, 0x1000L);
      case 'e':
         return jjMoveStringLiteralDfa14_0(active1, 0x400000000000000L, active2, 0x4000L);
      case 's':
         return jjMoveStringLiteralDfa14_0(active1, 0x0L, active2, 0x400L);
      default :
         break;
   }
   return jjStartNfa_0(12, 0L, active1, active2);
}
private int jjMoveStringLiteralDfa14_0(long old1, long active1, long old2, long active2){
   if (((active1 &= old1) | (active2 &= old2)) == 0L)
      return jjStartNfa_0(12, 0L, old1, old2);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(13, 0L, active1, active2);
      return 14;
   }
   switch(curChar)
   {
      case 'd':
         return jjMoveStringLiteralDfa15_0(active1, 0x400000000000000L, active2, 0x4000L);
      case 's':
         return jjMoveStringLiteralDfa15_0(active1, 0x0L, active2, 0x1400L);
      default :
         break;
   }
   return jjStartNfa_0(13, 0L, active1, active2);
}
private int jjMoveStringLiteralDfa15_0(long old1, long active1, long old2, long active2){
   if (((active1 &= old1) | (active2 &= old2)) == 0L)
      return jjStartNfa_0(13, 0L, old1, old2);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(14, 0L, active1, active2);
      return 15;
   }
   switch(curChar)
   {
      case '_':
         return jjMoveStringLiteralDfa16_0(active1, 0x400000000000000L, active2, 0x4000L);
      case 'i':
         return jjMoveStringLiteralDfa16_0(active1, 0x0L, active2, 0x400L);
      case 's':
         return jjMoveStringLiteralDfa16_0(active1, 0x0L, active2, 0x1000L);
      default :
         break;
   }
   return jjStartNfa_0(14, 0L, active1, active2);
}
private int jjMoveStringLiteralDfa16_0(long old1, long active1, long old2, long active2){
   if (((active1 &= old1) | (active2 &= old2)) == 0L)
      return jjStartNfa_0(14, 0L, old1, old2);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(15, 0L, active1, active2);
      return 16;
   }
   switch(curChar)
   {
      case 'g':
         return jjMoveStringLiteralDfa17_0(active1, 0x0L, active2, 0x400L);
      case 'i':
         return jjMoveStringLiteralDfa17_0(active1, 0x0L, active2, 0x1000L);
      case 's':
         return jjMoveStringLiteralDfa17_0(active1, 0x400000000000000L, active2, 0x4000L);
      default :
         break;
   }
   return jjStartNfa_0(15, 0L, active1, active2);
}
private int jjMoveStringLiteralDfa17_0(long old1, long active1, long old2, long active2){
   if (((active1 &= old1) | (active2 &= old2)) == 0L)
      return jjStartNfa_0(15, 0L, old1, old2);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(16, 0L, active1, active2);
      return 17;
   }
   switch(curChar)
   {
      case 'g':
         return jjMoveStringLiteralDfa18_0(active1, 0x0L, active2, 0x1000L);
      case 'h':
         return jjMoveStringLiteralDfa18_0(active1, 0x400000000000000L, active2, 0x4000L);
      case 'n':
         if ((active2 & 0x400L) != 0x0L)
            return jjStopAtPos(17, 138);
         break;
      default :
         break;
   }
   return jjStartNfa_0(16, 0L, active1, active2);
}
private int jjMoveStringLiteralDfa18_0(long old1, long active1, long old2, long active2){
   if (((active1 &= old1) | (active2 &= old2)) == 0L)
      return jjStartNfa_0(16, 0L, old1, old2);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(17, 0L, active1, active2);
      return 18;
   }
   switch(curChar)
   {
      case 'i':
         return jjMoveStringLiteralDfa19_0(active1, 0x400000000000000L, active2, 0x4000L);
      case 'n':
         if ((active2 & 0x1000L) != 0x0L)
            return jjStopAtPos(18, 140);
         break;
      default :
         break;
   }
   return jjStartNfa_0(17, 0L, active1, active2);
}
private int jjMoveStringLiteralDfa19_0(long old1, long active1, long old2, long active2){
   if (((active1 &= old1) | (active2 &= old2)) == 0L)
      return jjStartNfa_0(17, 0L, old1, old2);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(18, 0L, active1, active2);
      return 19;
   }
   switch(curChar)
   {
      case 'f':
         return jjMoveStringLiteralDfa20_0(active1, 0x400000000000000L, active2, 0x4000L);
      default :
         break;
   }
   return jjStartNfa_0(18, 0L, active1, active2);
}
private int jjMoveStringLiteralDfa20_0(long old1, long active1, long old2, long active2){
   if (((active1 &= old1) | (active2 &= old2)) == 0L)
      return jjStartNfa_0(18, 0L, old1, old2);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(19, 0L, active1, active2);
      return 20;
   }
   switch(curChar)
   {
      case 't':
         if ((active1 & 0x400000000000000L) != 0x0L)
         {
            jjmatchedKind = 122;
            jjmatchedPos = 20;
         }
         return jjMoveStringLiteralDfa21_0(active1, 0x0L, active2, 0x4000L);
      default :
         break;
   }
   return jjStartNfa_0(19, 0L, active1, active2);
}
private int jjMoveStringLiteralDfa21_0(long old1, long active1, long old2, long active2){
   if (((active1 &= old1) | (active2 &= old2)) == 0L)
      return jjStartNfa_0(19, 0L, old1, old2);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(20, 0L, 0L, active2);
      return 21;
   }
   switch(curChar)
   {
      case '_':
         return jjMoveStringLiteralDfa22_0(active2, 0x4000L);
      default :
         break;
   }
   return jjStartNfa_0(20, 0L, 0L, active2);
}
private int jjMoveStringLiteralDfa22_0(long old2, long active2){
   if (((active2 &= old2)) == 0L)
      return jjStartNfa_0(20, 0L, 0L, old2);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(21, 0L, 0L, active2);
      return 22;
   }
   switch(curChar)
   {
      case 'a':
         return jjMoveStringLiteralDfa23_0(active2, 0x4000L);
      default :
         break;
   }
   return jjStartNfa_0(21, 0L, 0L, active2);
}
private int jjMoveStringLiteralDfa23_0(long old2, long active2){
   if (((active2 &= old2)) == 0L)
      return jjStartNfa_0(21, 0L, 0L, old2);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(22, 0L, 0L, active2);
      return 23;
   }
   switch(curChar)
   {
      case 's':
         return jjMoveStringLiteralDfa24_0(active2, 0x4000L);
      default :
         break;
   }
   return jjStartNfa_0(22, 0L, 0L, active2);
}
private int jjMoveStringLiteralDfa24_0(long old2, long active2){
   if (((active2 &= old2)) == 0L)
      return jjStartNfa_0(22, 0L, 0L, old2);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(23, 0L, 0L, active2);
      return 24;
   }
   switch(curChar)
   {
      case 's':
         return jjMoveStringLiteralDfa25_0(active2, 0x4000L);
      default :
         break;
   }
   return jjStartNfa_0(23, 0L, 0L, active2);
}
private int jjMoveStringLiteralDfa25_0(long old2, long active2){
   if (((active2 &= old2)) == 0L)
      return jjStartNfa_0(23, 0L, 0L, old2);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(24, 0L, 0L, active2);
      return 25;
   }
   switch(curChar)
   {
      case 'i':
         return jjMoveStringLiteralDfa26_0(active2, 0x4000L);
      default :
         break;
   }
   return jjStartNfa_0(24, 0L, 0L, active2);
}
private int jjMoveStringLiteralDfa26_0(long old2, long active2){
   if (((active2 &= old2)) == 0L)
      return jjStartNfa_0(24, 0L, 0L, old2);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(25, 0L, 0L, active2);
      return 26;
   }
   switch(curChar)
   {
      case 'g':
         return jjMoveStringLiteralDfa27_0(active2, 0x4000L);
      default :
         break;
   }
   return jjStartNfa_0(25, 0L, 0L, active2);
}
private int jjMoveStringLiteralDfa27_0(long old2, long active2){
   if (((active2 &= old2)) == 0L)
      return jjStartNfa_0(25, 0L, 0L, old2);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(26, 0L, 0L, active2);
      return 27;
   }
   switch(curChar)
   {
      case 'n':
         if ((active2 & 0x4000L) != 0x0L)
            return jjStopAtPos(27, 142);
         break;
      default :
         break;
   }
   return jjStartNfa_0(26, 0L, 0L, active2);
}
private int jjStartNfaWithStates_0(int pos, int kind, int state)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) { return pos + 1; }
   return jjMoveNfa_0(state, pos + 1);
}
static final long[] jjbitVec0 = {
   0x0L, 0x0L, 0xffffffffffffffffL, 0xffffffffffffffffL
};
static final long[] jjbitVec1 = {
   0xfffffffffffffffeL, 0xffffffffffffffffL, 0xffffffffffffffffL, 0xffffffffffffffffL
};
static final long[] jjbitVec3 = {
   0x1ff00000fffffffeL, 0xffffffffffffc000L, 0xffffffffL, 0x600000000000000L
};
static final long[] jjbitVec4 = {
   0x0L, 0x0L, 0x0L, 0xff7fffffff7fffffL
};
static final long[] jjbitVec5 = {
   0x0L, 0xffffffffffffffffL, 0xffffffffffffffffL, 0xffffffffffffffffL
};
static final long[] jjbitVec6 = {
   0xffffffffffffffffL, 0xffffffffffffffffL, 0xffffL, 0x0L
};
static final long[] jjbitVec7 = {
   0xffffffffffffffffL, 0xffffffffffffffffL, 0x0L, 0x0L
};
static final long[] jjbitVec8 = {
   0x3fffffffffffL, 0x0L, 0x0L, 0x0L
};
private int jjMoveNfa_0(int startState, int curPos)
{
   int startsAt = 0;
   jjnewStateCnt = 73;
   int i = 1;
   jjstateSet[0] = startState;
   int kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         do
         {
            switch(jjstateSet[--i])
            {
               case 62:
                  if (curChar == 42)
                     { jjCheckNAddTwoStates(68, 69); }
                  else if (curChar == 47)
                  {
                     if (kind > 7)
                        kind = 7;
                     { jjCheckNAddStates(0, 2); }
                  }
                  break;
               case 6:
                  if ((0x1ffffffffL & l) != 0x0L)
                  {
                     if (kind > 6)
                        kind = 6;
                     { jjCheckNAdd(0); }
                  }
                  else if ((0x3ff000000000000L & l) != 0x0L)
                     { jjCheckNAddStates(3, 10); }
                  else if (curChar == 47)
                     { jjAddStates(11, 12); }
                  else if (curChar == 36)
                  {
                     if (kind > 72)
                        kind = 72;
                     { jjCheckNAdd(35); }
                  }
                  else if (curChar == 34)
                     jjstateSet[jjnewStateCnt++] = 32;
                  else if (curChar == 39)
                     { jjCheckNAddStates(13, 15); }
                  else if (curChar == 46)
                     { jjCheckNAdd(11); }
                  else if (curChar == 35)
                     jjstateSet[jjnewStateCnt++] = 1;
                  if ((0x3fe000000000000L & l) != 0x0L)
                  {
                     if (kind > 61)
                        kind = 61;
                     { jjCheckNAddTwoStates(8, 9); }
                  }
                  else if (curChar == 48)
                  {
                     if (kind > 61)
                        kind = 61;
                     { jjCheckNAddStates(16, 19); }
                  }
                  else if (curChar == 34)
                     { jjCheckNAddStates(20, 22); }
                  break;
               case 0:
                  if ((0x1ffffffffL & l) == 0x0L)
                     break;
                  if (kind > 6)
                     kind = 6;
                  { jjCheckNAdd(0); }
                  break;
               case 1:
                  if (curChar == 33)
                     { jjCheckNAddStates(23, 25); }
                  break;
               case 2:
                  if ((0xffffffffffffdbffL & l) != 0x0L)
                     { jjCheckNAddStates(23, 25); }
                  break;
               case 3:
                  if ((0x2400L & l) != 0x0L && kind > 8)
                     kind = 8;
                  break;
               case 4:
                  if (curChar == 10 && kind > 8)
                     kind = 8;
                  break;
               case 5:
                  if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 4;
                  break;
               case 7:
                  if ((0x3fe000000000000L & l) == 0x0L)
                     break;
                  if (kind > 61)
                     kind = 61;
                  { jjCheckNAddTwoStates(8, 9); }
                  break;
               case 8:
                  if ((0x3ff000000000000L & l) == 0x0L)
                     break;
                  if (kind > 61)
                     kind = 61;
                  { jjCheckNAddTwoStates(8, 9); }
                  break;
               case 10:
                  if (curChar == 46)
                     { jjCheckNAdd(11); }
                  break;
               case 11:
                  if ((0x3ff000000000000L & l) == 0x0L)
                     break;
                  if (kind > 66)
                     kind = 66;
                  { jjCheckNAddStates(26, 28); }
                  break;
               case 13:
                  if ((0x280000000000L & l) != 0x0L)
                     { jjCheckNAdd(14); }
                  break;
               case 14:
                  if ((0x3ff000000000000L & l) == 0x0L)
                     break;
                  if (kind > 66)
                     kind = 66;
                  { jjCheckNAddTwoStates(14, 15); }
                  break;
               case 16:
                  if (curChar == 39)
                     { jjCheckNAddStates(13, 15); }
                  break;
               case 17:
                  if ((0xffffff7fffffdbffL & l) != 0x0L)
                     { jjCheckNAddStates(13, 15); }
                  break;
               case 19:
                  { jjCheckNAddStates(13, 15); }
                  break;
               case 20:
                  if (curChar == 39 && kind > 69)
                     kind = 69;
                  break;
               case 21:
                  if (curChar == 34)
                     { jjCheckNAddStates(20, 22); }
                  break;
               case 22:
                  if ((0xfffffffbffffdbffL & l) != 0x0L)
                     { jjCheckNAddStates(20, 22); }
                  break;
               case 24:
                  { jjCheckNAddStates(20, 22); }
                  break;
               case 25:
                  if (curChar == 34 && kind > 70)
                     kind = 70;
                  break;
               case 26:
               case 28:
                  if (curChar == 34)
                     { jjCheckNAddTwoStates(27, 31); }
                  break;
               case 27:
                  if ((0xfffffffbffffffffL & l) != 0x0L)
                     { jjCheckNAddStates(29, 31); }
                  break;
               case 29:
                  if (curChar == 34 && kind > 71)
                     kind = 71;
                  break;
               case 30:
                  if (curChar == 34)
                     jjstateSet[jjnewStateCnt++] = 29;
                  break;
               case 31:
                  if (curChar == 34)
                     jjstateSet[jjnewStateCnt++] = 30;
                  break;
               case 32:
                  if (curChar == 34)
                     jjstateSet[jjnewStateCnt++] = 26;
                  break;
               case 33:
                  if (curChar == 34)
                     jjstateSet[jjnewStateCnt++] = 32;
                  break;
               case 34:
                  if (curChar != 36)
                     break;
                  if (kind > 72)
                     kind = 72;
                  { jjCheckNAdd(35); }
                  break;
               case 35:
                  if ((0x3ff001000000000L & l) == 0x0L)
                     break;
                  if (kind > 72)
                     kind = 72;
                  { jjCheckNAdd(35); }
                  break;
               case 36:
                  if ((0x3ff000000000000L & l) != 0x0L)
                     { jjCheckNAddStates(3, 10); }
                  break;
               case 37:
                  if ((0x3ff000000000000L & l) != 0x0L)
                     { jjCheckNAddTwoStates(37, 38); }
                  break;
               case 38:
                  if (curChar == 46)
                     { jjCheckNAdd(39); }
                  break;
               case 39:
                  if ((0x3ff000000000000L & l) == 0x0L)
                     break;
                  if (kind > 66)
                     kind = 66;
                  { jjCheckNAddStates(32, 34); }
                  break;
               case 41:
                  if ((0x280000000000L & l) != 0x0L)
                     { jjCheckNAdd(42); }
                  break;
               case 42:
                  if ((0x3ff000000000000L & l) == 0x0L)
                     break;
                  if (kind > 66)
                     kind = 66;
                  { jjCheckNAddTwoStates(42, 15); }
                  break;
               case 43:
                  if ((0x3ff000000000000L & l) != 0x0L)
                     { jjCheckNAddTwoStates(43, 44); }
                  break;
               case 44:
                  if (curChar == 46)
                     jjstateSet[jjnewStateCnt++] = 45;
                  break;
               case 46:
                  if ((0x280000000000L & l) != 0x0L)
                     { jjCheckNAdd(47); }
                  break;
               case 47:
                  if ((0x3ff000000000000L & l) == 0x0L)
                     break;
                  if (kind > 66)
                     kind = 66;
                  { jjCheckNAddTwoStates(47, 15); }
                  break;
               case 48:
                  if ((0x3ff000000000000L & l) != 0x0L)
                     { jjCheckNAddTwoStates(48, 49); }
                  break;
               case 50:
                  if ((0x280000000000L & l) != 0x0L)
                     { jjCheckNAdd(51); }
                  break;
               case 51:
                  if ((0x3ff000000000000L & l) == 0x0L)
                     break;
                  if (kind > 66)
                     kind = 66;
                  { jjCheckNAddTwoStates(51, 15); }
                  break;
               case 52:
                  if ((0x3ff000000000000L & l) != 0x0L)
                     { jjCheckNAddTwoStates(52, 53); }
                  break;
               case 54:
                  if (curChar != 48)
                     break;
                  if (kind > 61)
                     kind = 61;
                  { jjCheckNAddStates(16, 19); }
                  break;
               case 56:
                  if ((0x3ff000000000000L & l) == 0x0L)
                     break;
                  if (kind > 61)
                     kind = 61;
                  { jjCheckNAddTwoStates(56, 9); }
                  break;
               case 58:
                  if ((0x3000000000000L & l) == 0x0L)
                     break;
                  if (kind > 61)
                     kind = 61;
                  { jjCheckNAddStates(35, 37); }
                  break;
               case 59:
                  if ((0x3000000000000L & l) == 0x0L)
                     break;
                  if (kind > 61)
                     kind = 61;
                  { jjCheckNAdd(9); }
                  break;
               case 60:
                  if ((0xff000000000000L & l) == 0x0L)
                     break;
                  if (kind > 61)
                     kind = 61;
                  { jjCheckNAddTwoStates(60, 9); }
                  break;
               case 61:
                  if (curChar == 47)
                     { jjAddStates(11, 12); }
                  break;
               case 63:
                  if ((0xffffffffffffdbffL & l) == 0x0L)
                     break;
                  if (kind > 7)
                     kind = 7;
                  { jjCheckNAddStates(0, 2); }
                  break;
               case 64:
                  if ((0x2400L & l) != 0x0L && kind > 7)
                     kind = 7;
                  break;
               case 65:
                  if (curChar == 10 && kind > 7)
                     kind = 7;
                  break;
               case 66:
                  if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 65;
                  break;
               case 67:
                  if (curChar == 42)
                     { jjCheckNAddTwoStates(68, 69); }
                  break;
               case 68:
                  if ((0xfffffbffffffffffL & l) != 0x0L)
                     { jjCheckNAddTwoStates(68, 69); }
                  break;
               case 69:
                  if (curChar == 42)
                     { jjCheckNAddStates(38, 40); }
                  break;
               case 70:
                  if ((0xffff7bffffffffffL & l) != 0x0L)
                     { jjCheckNAddTwoStates(71, 69); }
                  break;
               case 71:
                  if ((0xfffffbffffffffffL & l) != 0x0L)
                     { jjCheckNAddTwoStates(71, 69); }
                  break;
               case 72:
                  if (curChar == 47 && kind > 9)
                     kind = 9;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 6:
               case 35:
                  if ((0x7fffffe87fffffeL & l) == 0x0L)
                     break;
                  if (kind > 72)
                     kind = 72;
                  { jjCheckNAdd(35); }
                  break;
               case 2:
                  { jjAddStates(23, 25); }
                  break;
               case 8:
                  if (curChar != 95)
                     break;
                  if (kind > 61)
                     kind = 61;
                  { jjCheckNAddTwoStates(8, 9); }
                  break;
               case 9:
                  if ((0x88920000889200L & l) != 0x0L && kind > 61)
                     kind = 61;
                  break;
               case 12:
                  if ((0x2000000020L & l) != 0x0L)
                     { jjAddStates(41, 42); }
                  break;
               case 15:
                  if ((0x80005000800050L & l) != 0x0L && kind > 66)
                     kind = 66;
                  break;
               case 17:
                  if ((0xffffffffefffffffL & l) != 0x0L)
                     { jjCheckNAddStates(13, 15); }
                  break;
               case 18:
                  if (curChar == 92)
                     jjstateSet[jjnewStateCnt++] = 19;
                  break;
               case 19:
                  { jjCheckNAddStates(13, 15); }
                  break;
               case 22:
                  if ((0xffffffffefffffffL & l) != 0x0L)
                     { jjCheckNAddStates(20, 22); }
                  break;
               case 23:
                  if (curChar == 92)
                     jjstateSet[jjnewStateCnt++] = 24;
                  break;
               case 24:
                  { jjCheckNAddStates(20, 22); }
                  break;
               case 27:
                  { jjAddStates(29, 31); }
                  break;
               case 40:
                  if ((0x2000000020L & l) != 0x0L)
                     { jjAddStates(43, 44); }
                  break;
               case 45:
                  if ((0x2000000020L & l) != 0x0L)
                     { jjAddStates(45, 46); }
                  break;
               case 49:
                  if ((0x2000000020L & l) != 0x0L)
                     { jjAddStates(47, 48); }
                  break;
               case 53:
                  if ((0x5000000050L & l) != 0x0L && kind > 66)
                     kind = 66;
                  break;
               case 55:
                  if ((0x100000001000000L & l) != 0x0L)
                     { jjCheckNAdd(56); }
                  break;
               case 56:
                  if ((0x7e8000007eL & l) == 0x0L)
                     break;
                  if (kind > 61)
                     kind = 61;
                  { jjCheckNAddTwoStates(56, 9); }
                  break;
               case 57:
                  if ((0x400000004L & l) == 0x0L)
                     break;
                  if (kind > 61)
                     kind = 61;
                  { jjCheckNAddStates(35, 37); }
                  break;
               case 58:
                  if (curChar != 95)
                     break;
                  if (kind > 61)
                     kind = 61;
                  { jjCheckNAddStates(35, 37); }
                  break;
               case 63:
                  if (kind > 7)
                     kind = 7;
                  { jjAddStates(0, 2); }
                  break;
               case 68:
                  { jjCheckNAddTwoStates(68, 69); }
                  break;
               case 70:
               case 71:
                  { jjCheckNAddTwoStates(71, 69); }
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int hiByte = (curChar >> 8);
         int i1 = hiByte >> 6;
         long l1 = 1L << (hiByte & 077);
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 6:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2))
                  {
                     if (kind > 6)
                        kind = 6;
                     { jjCheckNAdd(0); }
                  }
                  if (jjCanMove_2(hiByte, i1, i2, l1, l2))
                  {
                     if (kind > 72)
                        kind = 72;
                     { jjCheckNAdd(35); }
                  }
                  break;
               case 0:
                  if (!jjCanMove_0(hiByte, i1, i2, l1, l2))
                     break;
                  if (kind > 6)
                     kind = 6;
                  { jjCheckNAdd(0); }
                  break;
               case 2:
                  if (jjCanMove_1(hiByte, i1, i2, l1, l2))
                     { jjAddStates(23, 25); }
                  break;
               case 17:
               case 19:
                  if (jjCanMove_1(hiByte, i1, i2, l1, l2))
                     { jjCheckNAddStates(13, 15); }
                  break;
               case 22:
               case 24:
                  if (jjCanMove_1(hiByte, i1, i2, l1, l2))
                     { jjCheckNAddStates(20, 22); }
                  break;
               case 27:
                  if (jjCanMove_1(hiByte, i1, i2, l1, l2))
                     { jjAddStates(29, 31); }
                  break;
               case 34:
               case 35:
                  if (!jjCanMove_2(hiByte, i1, i2, l1, l2))
                     break;
                  if (kind > 72)
                     kind = 72;
                  { jjCheckNAdd(35); }
                  break;
               case 63:
                  if (!jjCanMove_1(hiByte, i1, i2, l1, l2))
                     break;
                  if (kind > 7)
                     kind = 7;
                  { jjAddStates(0, 2); }
                  break;
               case 68:
                  if (jjCanMove_1(hiByte, i1, i2, l1, l2))
                     { jjCheckNAddTwoStates(68, 69); }
                  break;
               case 70:
               case 71:
                  if (jjCanMove_1(hiByte, i1, i2, l1, l2))
                     { jjCheckNAddTwoStates(71, 69); }
                  break;
               default : if (i1 == 0 || l1 == 0 || i2 == 0 ||  l2 == 0) break; else break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      i = jjnewStateCnt;
      jjnewStateCnt = startsAt;
      startsAt = 73 - jjnewStateCnt;
      if (i == startsAt)
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(final java.io.IOException e) { return curPos; }
   }
}

/** Token literal values. */
public static final String[] jjstrLiteralImages = {
"", null, null, null, null, null, null, null, null, null,
"\141\142\163\164\162\141\143\164", "\142\157\157\154\145\141\156", "\142\162\145\141\153", "\143\154\141\163\163",
"\142\171\164\145", "\143\141\163\145", "\143\141\164\143\150", "\143\150\141\162",
"\143\157\156\163\164", "\143\157\156\164\151\156\165\145", "\144\145\146\141\165\154\164", "\144\157",
"\144\157\165\142\154\145", "\145\154\163\145", "\145\156\165\155", "\145\170\164\145\156\144\163",
"\146\141\154\163\145", "\146\151\156\141\154", "\146\151\156\141\154\154\171", "\146\154\157\141\164",
"\146\157\162", "\147\157\164\157", "\151\146", "\151\155\160\154\145\155\145\156\164\163",
"\151\155\160\157\162\164", "\151\156\163\164\141\156\143\145\157\146", "\151\156\164",
"\151\156\164\145\162\146\141\143\145", "\154\157\156\147", "\156\141\164\151\166\145", "\156\145\167",
"\156\165\154\154", "\160\141\143\153\141\147\145", "\160\162\151\166\141\164\145",
"\160\162\157\164\145\143\164\145\144", "\160\165\142\154\151\143", "\162\145\164\165\162\156", "\163\150\157\162\164",
"\163\164\141\164\151\143", "\163\164\162\151\143\164\146\160", "\163\167\151\164\143\150",
"\163\171\156\143\150\162\157\156\151\172\145\144", "\164\162\141\156\163\151\145\156\164", "\164\150\162\157\167",
"\164\150\162\157\167\163", "\164\162\165\145", "\164\162\171", "\166\157\151\144",
"\166\157\154\141\164\151\154\145", "\167\150\145\156", "\167\150\151\154\145", null, null, null, null, null, null,
null, null, null, null, null, null, null, null, "\50", "\51", "\173", "\175", "\133",
"\135", "\73", "\54", "\56", "\75", "\76", "\100\147\164", "\74", "\100\154\164",
"\41", "\176", "\75\75", "\74\75", "\100\154\164\145\161", "\76\75",
"\100\147\164\145\161", "\41\75", "\174\174", "\100\157\162", "\46\46", "\100\141\156\144", "\53\53",
"\55\55", "\53", "\55", "\52", "\57", "\46",
"\100\142\151\164\167\151\163\145\137\141\156\144", "\174", "\100\142\151\164\167\151\163\145\137\157\162", "\136",
"\100\142\151\164\167\151\163\145\137\170\157\162", "\45", "\100\155\157\144", "\52\52", "\100\160\157\167", "\74\74",
"\100\154\145\146\164\137\163\150\151\146\164", "\76\76", "\100\162\151\147\150\164\137\163\150\151\146\164", "\76\76\76",
"\100\162\151\147\150\164\137\165\156\163\151\147\156\145\144\137\163\150\151\146\164", "\53\75", "\55\75", "\52\75", "\57\75", "\46\75",
"\100\141\156\144\137\141\163\163\151\147\156", "\174\75", "\100\157\162\137\141\163\163\151\147\156", "\136\75",
"\100\170\157\162\137\141\163\163\151\147\156", "\45\75", "\100\155\157\144\137\141\163\163\151\147\156", "\52\52\75",
"\100\160\157\167\137\141\163\163\151\147\156", "\74\74\75",
"\100\154\145\146\164\137\163\150\151\146\164\137\141\163\163\151\147\156", "\76\76\75",
"\100\162\151\147\150\164\137\163\150\151\146\164\137\141\163\163\151\147\156", "\76\76\76\75",
"\100\162\151\147\150\164\137\165\156\163\151\147\156\145\144\137\163\150\151\146\164\137\141\163\163\151\147\156", "\55\76", "\74\75\76", "\77\77\75", "\77\77", "\77\72", "\77", "\72", "\72\72",
"\56\56\56", "\77\56", "\144\145\146\141\165\154\164\72", };
protected Token jjFillToken()
{
   final Token t;
   final String curTokenImage;
   final int beginLine;
   final int endLine;
   final int beginColumn;
   final int endColumn;
   String im = jjstrLiteralImages[jjmatchedKind];
   curTokenImage = im == null ? input_stream.getImage() : im;
   beginLine = input_stream.getBeginLine();
   beginColumn = input_stream.getBeginColumn();
   endLine = input_stream.getEndLine();
   endColumn = input_stream.getEndColumn();
   t = Token.newToken(jjmatchedKind);
   t.kind = jjmatchedKind;
   t.image = curTokenImage;

   t.beginLine = beginLine;
   t.endLine = endLine;
   t.beginColumn = beginColumn;
   t.endColumn = endColumn;

   return t;
}
static final int[] jjnextStates = {
   63, 64, 66, 37, 38, 43, 44, 48, 49, 52, 53, 62, 67, 17, 18, 20,
   55, 57, 60, 9, 22, 23, 25, 2, 3, 5, 11, 12, 15, 27, 28, 31,
   39, 40, 15, 58, 59, 9, 69, 70, 72, 13, 14, 41, 42, 46, 47, 50,
   51,
};
private static final boolean jjCanMove_0(int hiByte, int i1, int i2, long l1, long l2)
{
   switch(hiByte)
   {
      case 0:
         return ((jjbitVec0[i2] & l2) != 0L);
      default :
         return false;
   }
}
private static final boolean jjCanMove_1(int hiByte, int i1, int i2, long l1, long l2)
{
   switch(hiByte)
   {
      case 0:
         return ((jjbitVec0[i2] & l2) != 0L);
      default :
         if ((jjbitVec1[i1] & l1) != 0L)
            return true;
         return false;
   }
}
private static final boolean jjCanMove_2(int hiByte, int i1, int i2, long l1, long l2)
{
   switch(hiByte)
   {
      case 0:
         return ((jjbitVec4[i2] & l2) != 0L);
      case 48:
         return ((jjbitVec5[i2] & l2) != 0L);
      case 49:
         return ((jjbitVec6[i2] & l2) != 0L);
      case 51:
         return ((jjbitVec7[i2] & l2) != 0L);
      case 61:
         return ((jjbitVec8[i2] & l2) != 0L);
      default :
         if ((jjbitVec3[i1] & l1) != 0L)
            return true;
         return false;
   }
}

int curLexState = 0;
int defaultLexState = 0;
int jjnewStateCnt;
int jjround;
int jjmatchedPos;
int jjmatchedKind;

/** Get the next Token. */
public Token getNextToken()
{
  Token specialToken = null;
  Token matchedToken;
  int curPos = 0;

  EOFLoop:
  for (;;)
  {
   try
   {
      curChar = input_stream.beginToken();
   }
   catch(final Exception e)
   {
      jjmatchedKind = 0;
      jjmatchedPos = -1;
      matchedToken = jjFillToken();
      matchedToken.specialToken = specialToken;
      return matchedToken;
   }

   jjmatchedKind = 0x7fffffff;
   jjmatchedPos = 0;
   curPos = jjMoveStringLiteralDfa0_0();
   if (jjmatchedKind != 0x7fffffff)
   {
      if (jjmatchedPos + 1 < curPos)
         input_stream.backup(curPos - jjmatchedPos - 1);
      if ((jjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
      {
         matchedToken = jjFillToken();
         matchedToken.specialToken = specialToken;
         return matchedToken;
      }
      else
      {
         if ((jjtoSpecial[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
         {
            matchedToken = jjFillToken();
            if (specialToken == null)
               specialToken = matchedToken;
            else
            {
               matchedToken.specialToken = specialToken;
               specialToken = (specialToken.next = matchedToken);
            }
         }
         continue EOFLoop;
      }
   }
   int error_line = input_stream.getEndLine();
   int error_column = input_stream.getEndColumn();
   String error_after = null;
   boolean EOFSeen = false;
   try {
     input_stream.readChar();
     input_stream.backup(1);
   }
   catch (final java.io.IOException e1) {
      EOFSeen = true;
      error_after = curPos <= 1 ? "" : input_stream.getImage();
      if (curChar == '\n' || curChar == '\r') {
         error_line++;
         error_column = 0;
      }
      else
         error_column++;
   }
   if (!EOFSeen) {
      input_stream.backup(1);
      error_after = curPos <= 1 ? "" : input_stream.getImage();
   }
   throw new TokenMgrException(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrException.LEXICAL_ERROR);
  }
}

void SkipLexicalActions(Token matchedToken)
{
   switch(jjmatchedKind)
   {
      default :
         break;
   }
}
void MoreLexicalActions()
{
   jjimageLen += (lengthOfMatch = jjmatchedPos + 1);
   switch(jjmatchedKind)
   {
      default :
         break;
   }
}
void TokenLexicalActions(Token matchedToken)
{
   switch(jjmatchedKind)
   {
      default :
         break;
   }
}
private void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
private void jjAddStates(int start, int end)
{
   do {
      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
   } while (start++ != end);
}
private void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}

private void jjCheckNAddStates(int start, int end)
{
   do {
      jjCheckNAdd(jjnextStates[start]);
   } while (start++ != end);
}

    /** Constructor. */
    public ParserTokenManager(JavaCharStream stream){
    input_stream = stream;
  }

  /** Constructor. */
  public ParserTokenManager (JavaCharStream stream, int lexState){
    ReInit(stream);
    SwitchTo(lexState);
  }

  /** Reinitialise parser. */

  public void ReInit(JavaCharStream stream)
  {


    jjmatchedPos =
    jjnewStateCnt =
    0;
    curLexState = defaultLexState;
    input_stream = stream;
    ReInitRounds();
  }

  private void ReInitRounds()
  {
    int i;
    jjround = 0x80000001;
    for (i = 73; i-- > 0;)
      jjrounds[i] = 0x80000000;
  }

  /** Reinitialise parser. */
  public void ReInit(JavaCharStream stream, int lexState)
  {
    ReInit(stream);
    SwitchTo(lexState);
  }

  /** Switch to specified lex state. */
  public void SwitchTo(int lexState)
  {
    if (lexState >= 1 || lexState < 0)
      throw new TokenMgrException("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrException.INVALID_LEXICAL_STATE);
    else
      curLexState = lexState;
  }


/** Lexer state names. */
public static final String[] lexStateNames = {
   "DEFAULT",
};

/** Lex State array. */
public static final int[] jjnewLexState = {
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
   -1, -1, -1, -1,
};
static final long[] jjtoToken = {
   0x3ffffffffffffc01L, 0xfffffffffffff9e4L, 0x3ffffffL,
};
static final long[] jjtoSkip = {
   0x3feL, 0x0L, 0x0L,
};
static final long[] jjtoSpecial = {
   0x380L, 0x0L, 0x0L,
};
static final long[] jjtoMore = {
   0x0L, 0x0L, 0x0L,
};
    protected JavaCharStream  input_stream;

    private final int[] jjrounds = new int[73];
    private final int[] jjstateSet = new int[2 * 73];
    private final StringBuilder jjimage = new StringBuilder();
    private StringBuilder image = jjimage;
    private int jjimageLen;
    private int lengthOfMatch;
    protected int curChar;
}
